### ISSUE TITLE
Please set up jenkins for stratisd-client-dbus

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratisd-client-dbus#39]

**Comment by mulkieran** [comment]
@trgill Could you do this? Would be nice to officially run this test for new dbus-python-client interface.

**Comment by mulkieran** [comment]
@trgill Now that we know that it would have easily caught a bug in stratisd it seems like it would be even more useful to get it set up to run on some trigger or other.

**Comment by trgill** [comment]
@mulkieran looking at this

**Comment by mulkieran** [comment]
Whoops. wrong button.

**Comment by mulkieran** [comment]
This has been completed and the tests are running regularly against stratisd.
